[mypy]
plugins = mypy_django_plugin.main

django_settings_module = core_spoton.spoton_backend.settings

ignore_missing_imports = True
exclude = ^tests/.*$

[mypy.plugins.django-stubs]
django_settings_module = core_spoton.spoton_backend.settings
