# Generated by Django 5.2.8 on 2025-11-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_lecturehalls_lecturehall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturehall',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='lecturehall',
            name='operating_hours',
        ),
    ]
