# Generated by Django 5.2.8 on 2025-11-27 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('capacity_ratings', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=100)),
                ('has_power_outlets', models.BooleanField(default=False)),
                ('is_quiet', models.BooleanField(default=False)),
                ('operating_hours', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('capacity_ratings', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=100)),
                ('has_power_outlets', models.BooleanField(default=False)),
                ('is_quiet', models.BooleanField(default=False)),
                ('operating_hours', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'spot',
                'verbose_name_plural': 'spots',
                'ordering': ['is_approved'],
            },
        ),
        migrations.CreateModel(
            name='ClassFreeRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='No class', max_length=100)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_halls', to='api.lecturehalls')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.spot')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('GETTING FULL', 'Getting Full'), ('COMPLETELY FULL', 'Completely Full')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='api.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
