# Generated by Django 5.2.8 on 2025-11-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureHalls',
            new_name='LectureHall',
        ),
    ]
