# Generated by Django 5.2.8 on 2026-04-23 20:49

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lecturehall_location_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='has_power_outlets',
        ),
        migrations.AddField(
            model_name='spot',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
        migrations.CreateModel(
            name='SpotAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.amenities')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='api.spot')),
            ],
        ),
    ]
