# Generated by Django 5.2.8 on 2026-04-23 21:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_amenities_remove_spot_has_power_outlets_spot_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='amenity_name', unique=True),
        ),
    ]
