# Generated by Django 5.2.8 on 2026-04-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_amenities_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'ordering': ['amenity_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='classfreerooms',
            options={'ordering': ['day_of_week', '-end_time']},
        ),
        migrations.AlterModelOptions(
            name='lecturehall',
            options={'ordering': ['name', 'id'], 'verbose_name': 'lecture hall'},
        ),
        migrations.AlterModelOptions(
            name='spotamenities',
            options={'ordering': ['spot']},
        ),
        migrations.AlterModelOptions(
            name='statusreport',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='classfreerooms',
            index=models.Index(fields=['day_of_week'], name='api_classfr_day_of__1dc419_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturehall',
            index=models.Index(fields=['name'], name='api_lecture_name_403699_idx'),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['is_approved'], name='api_spot_is_appr_7a4a8d_idx'),
        ),
        migrations.AddField(
            model_name='savedspots',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.spot'),
        ),
        migrations.AddField(
            model_name='savedspots',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedspots',
            unique_together={('user', 'spot')},
        ),
    ]
